### ISSUE TITLE
R_RenderScene + 0x14

### ISSUE THREAD

**Issue by ssnob** [coxtristan/T7EditorClient#3]
stack traceback:
	1: in function 'helper' main.lua:10:23
	2: in function 'stub' main.lua:15:13
	3: in function 'calle' main.lua:20:5
	4: in function 'calle' main.lua:22:5
	5: in function 'helper' main.lua:27:23
	6: in function 'stub' main.lua:32:13
	7: in function 'calle' main.lua:37:5
	8: in function 'calle' main.lua:39:5
	9: in function 'helper' main.lua:44:23
   10: in function 'stub' main.lua:49:13
   11: in function 'calle' main.lua:54:5
   12: in function 'calle' main.lua:56:5
   13: in function 'helper' main.lua:61:23
   14: in function 'stub' main.lua:66:13
   15: in function 'calle' main.lua:71:5
   16: in function 'calle' main.lua:73:5
   17: in function 'main' main.lua:78:3

**Comment by shiversoftdev** [comment]
can confirm

**Comment by shiversoftdev** [comment]
is this ever getting fixed?

**Comment by nice-sprite** [comment]
Unfortunately
